
export const FETCHED_MEMBERS = Symbol('FETCHED_MEMBERS');
export const DISPLAY_MEMBERS = Symbol('DISPLAY_MEMBERS');

export const PROCESSING = Symbol('PROCESSING');

export const SEARCH_EXPANDED_COMMITTEE = Symbol('SEARCH_EXPANDED_COMMITTEE');
export const SEARCH_LEAD_COMMITTEE = Symbol('SEARCH_LEAD_COMMITTEE');
export const SEARCH_SCHEDULE_SESSION = Symbol('SEARCH_SCHEDULE_SESSION');

export const AVAILABLE_SESSION_SCHEDULES = Symbol('AVAILABLE_SESSION_SCHEDULES');

export const EDIT_COMMITTEE = Symbol("EDIT_COMMITTEE");
export const VIEW_SELECTED_FILE = Symbol("VIEW_SELECTED_FILE");
export const SOCKET_INSTANCE = Symbol("SOCKET_INSTANCE");

export const FIRST_DISTRICT = 1;
export const SECOND_DISTRICT = 2;